app:
  sort: false
  cache:
    size: 50
    expire: PT6H
  formats:
    - mp4
    - flv
    - avi
    - mkv
    - rm
    - rmvb
    - wmv
    - mpg
    - mpeg
    - mov
    - ts
    - mp3
    - m4a
    - ape
    - flac
    - wma
    - wav
  sites:
    - name: 本地
      url: http://192.168.50.10:5244
