spring:
  datasource:
    url: jdbc:h2:file:/data/atv
    username: sa
    password: password
    driverClassName: org.h2.Driver

app:
  sites:
    - name: 丫仙女
      url: http://localhost
      version: 3
      searchable: true
      xiaoya: true
