app:
  cache:
    size: 50
    expire: PT2H
  formats:
    - mp4
    - flv
    - avi
    - mkv
    - rm
    - rmvb
    - wmv
    - mpg
    - mpeg
    - mov
    - ts
    - mp3
    - m4a
    - ape
    - flac
    - wma
    - wav
